### PR TITLE
Add support for timeline

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Looks good but I don't see any documentation regarding timeline support in README or in the `rise-playlist.html` file for GH page documentation. Is this intentional for now?

**Comment by donnapep** [comment]
@stulees The documentation for timeline is in the timeline component - http://rise-vision.github.io/rise-timeline/components/rise-timeline/. I intentionally kept the usage example for playlist bare bones since not everyone will necessarily require distribution or timeline. Do you think that info needs to be repeated here?

**Comment by stulees** [comment]
@donnapep Probably not, just was thinking since you've used `<rise-timeline>` in your demo that maybe a mention of it in some way or a reference to the documentation on `<rise-timeline>` could be mentioned in README or component documentation. I'll defer to you :+1: Thanks

**Comment by donnapep** [comment]
@stulees I've added some additional text to the ReadMe. Thx.

**Comment by stulees** [comment]
@donnapep Nice :+1:

**Pull request merged**
