### PR TITLE
Upgrade to Polymer 1.0

### PR DESCRIPTION
**Pull request by donnapep**
- Upgrade Polymer.
- Prefix private members with _.
- Use canonical URLs.
- Update ReadMe to include instructions for running Polyserve.
- Call to `clock.useFakeTimers` in tests had to be moved to before the HTML import in order to be able to intercept calls to `setTimeout`.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Noticed you're using `setTimeout` instead of one of the Polymer 1.0 utility functions like `async` or `debounce`. I think moving forward we should leverage these. Otherwise, :+1:

**Comment by donnapep** [comment]
@stulees At the time I couldn't use their `job` function (renamed to `debounce`) because it didn't have a return value, and I need to be able to clear the timeout. I think that has changed now though, so I may switch to using `debounce` if it works for my needs.

**Comment by stulees** [comment]
@donnapep Yeah they now provide `cancelDebouncer(jobName)`, `flushDebouncer(jobName)`, and `isDebouncerActive(jobName)` which look good and should cover our needs. Here's the documentation on them - https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html

**Pull request merged**
